[tasks.go-build]
run = "go build -o dest/go-frontend ."

[tasks.go-push-frontend]
run = '''
docker build -t go-frontend:latest -f go-frontend.Dockerfile .
docker tag go-frontend:latest ghcr.io/coffee-cup/buildkit-frontends:go-frontend
docker push ghcr.io/coffee-cup/buildkit-frontends:go-frontend
'''

[tasks.go-run]
run = '''
buildctl build \
    --frontend=gateway.v0 \
    --local context=examples/node-npm-latest \
    --opt source=ghcr.io/coffee-cup/buildkit-frontends:go-frontend \
    --output type=docker,name=go-node | docker load
'''

[tasks.clean]
run = "rm -rf dest"

[tools.go]
version = "1.23.4"
